# Generated by Django 2.0.13 on 2020-01-06 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import pos.models


class Migration(migrations.Migration):

    replaces = [('pos', '0001_initial'), ('pos', '0002_store'), ('pos', '0003_auto_20191224_1519'), ('pos', '0004_sale'), ('pos', '0005_auto_20191225_0053'), ('pos', '0006_saleline'), ('pos', '0007_saleline_is_product_serial'), ('pos', '0008_auto_20191231_0841'), ('pos', '0009_auto_20191231_0935'), ('pos', '0010_remove_product_sell_price'), ('pos', '0011_auto_20200102_1149'), ('pos', '0012_auto_20200102_1246'), ('pos', '0013_remove_saleline_is_product_serial'), ('pos', '0014_remove_inventory_count'), ('pos', '0015_inventory_count'), ('pos', '0016_remove_pricelist_price'), ('pos', '0017_pricelist_price'), ('pos', '0018_auto_20200103_0528'), ('pos', '0019_auto_20200103_0600'), ('pos', '0020_auto_20200103_0831'), ('pos', '0021_auto_20200105_0546'), ('pos', '0022_product_hsncode'), ('pos', '0023_auto_20200105_0554'), ('pos', '0024_inventory_status'), ('pos', '0025_auto_20200105_1337'), ('pos', '0026_auto_20200105_1338'), ('pos', '0027_auto_20200105_1447'), ('pos', '0028_auto_20200106_0226'), ('pos', '0029_auto_20200106_0301'), ('pos', '0030_auto_20200106_0314'), ('pos', '0031_remove_store_position'), ('pos', '0032_store_position'), ('pos', '0033_remove_store_position'), ('pos', '0034_store_position'), ('pos', '0035_remove_store_position'), ('pos', '0036_store_position'), ('pos', '0037_remove_store_position')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_field_fix_and_editable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[pos.models.validate_product_name])),
                ('item_code', models.CharField(max_length=50, unique=True, verbose_name='Item Code')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='UPC Code')),
                ('hsncode', models.CharField(max_length=20, verbose_name='HSN Code')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organizations.Organization')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Store ID')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh ', 'Arunachal Pradesh '), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir ', 'Jammu and Kashmir '), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Lakshadweep', 'Lakshadweep'), ('National Capital Territory of Delhi', 'National Capital Territory of Delhi'), ('Puducherry', 'Puducherry')], max_length=80, verbose_name='State')),
                ('pincode', models.CharField(max_length=6, verbose_name='Pin-Code')),
                ('is_sale_location', models.BooleanField(default=True)),
                ('addr1', models.CharField(default='', max_length=200, verbose_name='Address 1')),
                ('addr2', models.CharField(max_length=200, verbose_name='Address 2')),
                ('addr3', models.CharField(max_length=200, verbose_name='Address 3')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Storage Location',
                'verbose_name_plural': 'Storage Locations',
                'abstract': False,
            },
            bases=('organizations.organization',),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Sale Completed'), (1, 'Sale in Progress'), (2, 'Sale Cancelled')], default=False, verbose_name='Sale Status')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(default=1, limit_choices_to={'is_deleted': False, 'is_sale_location': True}, on_delete=django.db.models.deletion.CASCADE, to='pos.Store')),
            ],
            options={
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Product')),
                ('saleorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Sale')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=2, max_digits=7)),
                ('serialbatchnumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='Serial / Batch Number')),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sale', 'Sale'), ('cost', 'Cost')], max_length=10, verbose_name='Price List Type')),
                ('serialbatchnumber', models.CharField(max_length=50, verbose_name='Serial/Batch Number')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='is_product_serial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UPC Code'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Product'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Product'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Store'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='serialbatchnumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Serial/Batch Number'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='sell_price',
        ),
        migrations.CreateModel(
            name='TaxesGST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsnname', models.CharField(max_length=20, verbose_name='HSN Code')),
                ('taxrate', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventory Lines'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='hsncode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='item_code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Item Code'),
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='count',
        ),
        migrations.AddField(
            model_name='inventory',
            name='count',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='price',
        ),
        migrations.AddField(
            model_name='pricelist',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='item_code',
            field=models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=100, validators=[pos.models.validate_product_name]),
        ),
        migrations.AddField(
            model_name='product',
            name='hsncode',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pos.TaxesGST'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.IntegerField(choices=[(0, 'In Store'), (1, 'Sold'), (2, 'In Transit')], default=0, verbose_name='Status'),
        ),
    ]
