# Generated by Django 2.2.7 on 2019-12-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_store'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Storage Location', 'verbose_name_plural': 'Storage Locations'},
        ),
        migrations.AddField(
            model_name='store',
            name='is_sale_location',
            field=models.BooleanField(default=True),
        ),
    ]
