# Generated by Django 2.0.13 on 2020-01-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_auto_20200106_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=22, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=22, null=True, verbose_name='Longitude'),
        ),
    ]
