# Generated by Django 2.0.13 on 2020-01-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_auto_20200106_0357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('phonenumber', models.CharField(max_length=12, verbose_name='Phone Number')),
            ],
        ),
    ]
