# Generated by Django 2.0.13 on 2020-01-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, default=True, max_length=100, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phonenumber',
            field=models.CharField(max_length=12, unique=True, verbose_name='Phone Number'),
        ),
    ]
