# Generated by Django 2.0.13 on 2019-12-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_auto_20191231_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='serialbatchnumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Serial/Batch Number'),
        ),
    ]
