# Generated by Django 2.0.13 on 2019-12-31 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_auto_20191231_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sell_price',
        ),
    ]
