# Generated by Django 2.0.13 on 2020-01-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_auto_20200102_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='item_code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='taxesgst',
            name='taxrate',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
