# Generated by Django 2.0.13 on 2020-01-03 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_auto_20200102_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleline',
            name='is_product_serial',
        ),
    ]
