# Generated by Django 2.0.13 on 2020-01-03 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_remove_saleline_is_product_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='count',
        ),
    ]
