# Generated by Django 2.0.13 on 2020-01-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_remove_inventory_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='count',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
            preserve_default=False,
        ),
    ]
