# Generated by Django 2.0.13 on 2020-01-03 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_inventory_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelist',
            name='price',
        ),
    ]
