# Generated by Django 2.0.13 on 2020-01-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_remove_pricelist_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
            preserve_default=False,
        ),
    ]
