# Generated by Django 2.0.13 on 2020-01-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_pricelist_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='addr',
        ),
        migrations.RemoveField(
            model_name='store',
            name='gstn',
        ),
        migrations.RemoveField(
            model_name='store',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='store',
            name='addr1',
            field=models.CharField(default='', max_length=200, verbose_name='Address 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='addr2',
            field=models.TextField(default='', max_length=200, verbose_name='Address 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='addr3',
            field=models.TextField(default='', max_length=200, verbose_name='Address 2'),
            preserve_default=False,
        ),
    ]
