# Generated by Django 2.0.13 on 2020-01-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_auto_20200103_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='addr2',
            field=models.CharField(max_length=200, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='store',
            name='addr3',
            field=models.CharField(max_length=200, verbose_name='Address 3'),
        ),
    ]
