# Generated by Django 2.0.13 on 2020-01-03 08:31

from django.db import migrations, models
import pos.models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0019_auto_20200103_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_code',
            field=models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=100, validators=[pos.models.validate_product_name]),
        ),
    ]
