# Generated by Django 2.0.13 on 2020-01-05 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_auto_20200103_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxesgst',
            old_name='hsncode',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hsncode',
        ),
    ]
