# Generated by Django 2.0.13 on 2020-01-05 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0025_auto_20200105_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Store ID'),
        ),
        migrations.AlterField(
            model_name='store',
            name='organization_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organizations.Organization'),
        ),
    ]
