# Generated by Django 2.0.13 on 2020-01-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0026_auto_20200105_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.IntegerField(choices=[(0, 'In Store'), (1, 'Sold'), (2, 'In Transit')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Store ID'),
        ),
    ]
