# Generated by Django 2.0.13 on 2020-01-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0027_auto_20200105_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='store',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
