# Generated by Django 2.0.13 on 2020-01-06 03:01

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0028_auto_20200106_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='store',
            name='lon',
        ),
        migrations.AddField(
            model_name='store',
            name='position',
            field=geoposition.fields.GeopositionField(default=None, max_length=42),
            preserve_default=False,
        ),
    ]
