# Generated by Django 2.0.13 on 2020-01-06 03:14

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0029_auto_20200106_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, default=None, max_length=42),
        ),
    ]
