# Generated by Django 2.0.13 on 2020-01-06 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0030_auto_20200106_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='position',
        ),
    ]
