# Generated by Django 2.0.13 on 2020-01-06 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0034_store_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='position',
        ),
    ]
