# Generated by Django 2.0.13 on 2020-01-06 03:34

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0035_remove_store_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, default='', max_length=42),
        ),
    ]
